spring.application.name=ShopKart
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/shopkart_db
spring.datasource.username=root
spring.datasource.password=your_password

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server
server.port=8082